/**
 * Client-side api_id → display name mapping for PoE2 currencies and items.
 *
 * PURPOSE:
 *   When the backend is online, flip responses include `currencyFromRu` /
 *   `currencyToRu` fields from `backend/data/currency_names_ru.py`.
 *   This file provides a FALLBACK for:
 *     1. Offline mode (backend down, only cache/prepopulated data available)
 *     2. Items not yet in the backend mapping
 *     3. Currencies table, exchange table, and other non-flip views
 *
 * USAGE:
 *   import { getCurrencyRuName, getCurrencyEnName } from "@/lib/currency-names";
 *   const ruName = getCurrencyRuName("exalted"); // "Благородная сфера"
 *
 * MAINTAINER NOTES:
 *   - Auto-synced from backend/data/currency_names_ru.py (iteration 32)
 *   - Source tags (# poe2db, # poedb) are stripped in this file for cleanliness
 *   - The full backend has 349 RU entries; this file mirrors all of them
 *   - PoE1-only items have been removed — this is a PoE2-only dashboard
 *   - 9 outdated fire/ice/lightning rune tier entries removed (PoE2 overhauled runes)
 *   - 5 items exist on poe2db but not in POE2Scout API (noted in backend)
 */

// ---------------------------------------------------------------------------
// api_id → Russian name (offline fallback)
// ---------------------------------------------------------------------------

const CURRENCY_NAMES_RU: Record<string, string> = {
  "exalted": "Благородная сфера",
  "chaos": "Сфера хаоса",
  "divine": "Божественная сфера",
  "vaal": "Сфера Ваала",
  "mirror": "Зеркало Каландры",
  "alch": "Сфера алхимика",
  "transmute": "Сфера превращения",
  "aug": "Сфера дополнения",
  "chance": "Сфера удачи",
  "annul": "Сфера аннулирования",
  "regal": "Коронованная сфера",
  "whetstone": "Точильный камень кузнеца",
  "scrap": "Кусок брони",
  "bauble": "Стеклодувная бусина",
  "gcp": "Призма резчика камней",
  "etcher": "Резец чародея",
  "artificers": "Сфера астромантии",
  "wisdom": "Свиток мудрости",
  "fracturing-orb": "Сфера раскалывания",
  "chance-shard": "Осколок удачи",
  "regal-shard": "Осколок коронованной сферы",
  "artificers-shard": "Осколок астромантии",
  "transmutation-shard": "Осколок сферы превращения",
  "greater-chaos-orb": "Большая сфера хаоса",
  "greater-exalted-orb": "Большая сфера возвышения",
  "greater-orb-of-transmutation": "Большая сфера превращения",
  "greater-orb-of-augmentation": "Большая сфера усиления",
  "greater-regal-orb": "Большая сфера царей",
  "greater-jewellers-orb": "Большая сфера златокузнеца",
  "lesser-jewellers-orb": "Малая сфера златокузнеца",
  "perfect-chaos-orb": "Совершенная сфера хаоса",
  "perfect-exalted-orb": "Совершенная сфера возвышения",
  "perfect-jewellers-orb": "Совершенная сфера златокузнеца",
  "perfect-orb-of-transmutation": "Совершенная сфера превращения",
  "perfect-orb-of-augmentation": "Совершенная сфера усиления",
  "perfect-regal-orb": "Совершенная сфера царей",
  "cryptic-key": "Скрытый ключ",
  "hinekoras-lock": "Прядь Хинекоры",
  "portal": "Свиток портала",
  "identify": "Свиток опознания",
  "scouring": "Сфера очищения",
  "regret": "Сфера сожаления",
  "fusings": "Сфера слияния",
  "chromatic": "Хроматическая сфера",
  "jeweller": "Сфера ювелира",
  "blessed": "Благословенная сфера",
  "eternal": "Вечная сфера",
  "silver": "Серебряная монета",
  "gold": "Золото",
  "perandus": "Монета Перандуса",
  "alteration": "Сфера перемен",
  "raven-touched-shard": "Осколок, тронутый вороном",
  "head-of-the-king": "Голова короля",
  "astrids-creativity": "Творчество Астрид",
  // NOTE: PoE2 runes overhauled — fire/ice/lightning tiers removed. New rune system
  // (adept/body/iron/mind/stone/storm + lesser/greater/perfect) needs RU names added later.
  "essence-of-horror": "Сущность ужаса",
  "essence-of-delirium": "Сущность бреда",
  "essence-of-hysteria": "Сущность истерии",
  "essence-of-insanity": "Сущность безумия",
  "essence-of-ice": "Сущность льда",
  "essence-of-flames": "Сущность пламени",
  "essence-of-the-mind": "Сущность разума",
  "essence-of-the-body": "Сущность тела",
  "essence-of-opulence": "Сущность изобилия",
  "essence-of-ruin": "Сущность гибели",
  "essence-of-battle": "Сущность битвы",
  "essence-of-sorcery": "Сущность колдовства",
  "essence-of-alacrity": "Сущность живости",
  "essence-of-command": "Сущность повеления",
  "essence-of-enhancement": "Сущность улучшения",
  "essence-of-electricity": "Сущность электричества",
  "essence-of-grounding": "Сущность заземления",
  "essence-of-haste": "Сущность спешки",
  "essence-of-insulation": "Сущность изоляции",
  "essence-of-seeking": "Сущность искания",
  "essence-of-thawing": "Сущность таяния",
  "essence-of-abrasion": "Сущность разрушения",
  "essence-of-the-abyss": "Сущность Бездны",
  "essence-of-the-breach": "Сущность Разлома",
  "essence-of-the-infinite": "Сущность бесконечности",
  "greater-essence-of-ice": "Большая сущность льда",
  "greater-essence-of-flames": "Большая сущность пламени",
  "greater-essence-of-the-mind": "Большая сущность разума",
  "greater-essence-of-the-body": "Большая сущность тела",
  "greater-essence-of-opulence": "Большая сущность изобилия",
  "greater-essence-of-ruin": "Большая сущность гибели",
  "greater-essence-of-battle": "Большая сущность битвы",
  "greater-essence-of-sorcery": "Большая сущность колдовства",
  "greater-essence-of-alacrity": "Большая сущность живости",
  "greater-essence-of-command": "Большая сущность повеления",
  "greater-essence-of-enhancement": "Большая сущность улучшения",
  "greater-essence-of-electricity": "Большая сущность электричества",
  "greater-essence-of-grounding": "Большая сущность заземления",
  "greater-essence-of-haste": "Большая сущность спешки",
  "greater-essence-of-insulation": "Большая сущность изоляции",
  "greater-essence-of-seeking": "Большая сущность искания",
  "greater-essence-of-thawing": "Большая сущность таяния",
  "greater-essence-of-abrasion": "Большая сущность разрушения",
  "greater-essence-of-the-infinite": "Большая сущность бесконечности",
  "lesser-essence-of-ice": "Малая сущность льда",
  "lesser-essence-of-flames": "Малая сущность пламени",
  "lesser-essence-of-the-mind": "Малая сущность разума",
  "lesser-essence-of-the-body": "Малая сущность тела",
  "lesser-essence-of-opulence": "Малая сущность изобилия",
  "lesser-essence-of-ruin": "Малая сущность гибели",
  "lesser-essence-of-battle": "Малая сущность битвы",
  "lesser-essence-of-sorcery": "Малая сущность колдовства",
  "lesser-essence-of-alacrity": "Малая сущность живости",
  "lesser-essence-of-command": "Малая сущность повеления",
  "lesser-essence-of-enhancement": "Малая сущность улучшения",
  "lesser-essence-of-electricity": "Малая сущность электричества",
  "lesser-essence-of-grounding": "Малая сущность заземления",
  "lesser-essence-of-haste": "Малая сущность спешки",
  "lesser-essence-of-insulation": "Малая сущность изоляции",
  "lesser-essence-of-seeking": "Малая сущность искания",
  "lesser-essence-of-thawing": "Малая сущность таяния",
  "lesser-essence-of-abrasion": "Малая сущность разрушения",
  "lesser-essence-of-the-infinite": "Малая сущность бесконечности",
  "perfect-essence-of-ice": "Совершенная сущность льда",
  "perfect-essence-of-flames": "Совершенная сущность пламени",
  "perfect-essence-of-the-mind": "Совершенная сущность разума",
  "perfect-essence-of-the-body": "Совершенная сущность тела",
  "perfect-essence-of-opulence": "Совершенная сущность изобилия",
  "perfect-essence-of-ruin": "Совершенная сущность гибели",
  "perfect-essence-of-battle": "Совершенная сущность битвы",
  "perfect-essence-of-sorcery": "Совершенная сущность колдовства",
  "perfect-essence-of-alacrity": "Совершенная сущность живости",
  "perfect-essence-of-command": "Совершенная сущность повеления",
  "perfect-essence-of-enhancement": "Совершенная сущность улучшения",
  "perfect-essence-of-electricity": "Совершенная сущность электричества",
  "perfect-essence-of-grounding": "Совершенная сущность заземления",
  "perfect-essence-of-haste": "Совершенная сущность спешки",
  "perfect-essence-of-insulation": "Совершенная сущность изоляции",
  "perfect-essence-of-seeking": "Совершенная сущность искания",
  "perfect-essence-of-thawing": "Совершенная сущность таяния",
  "perfect-essence-of-abrasion": "Совершенная сущность разрушения",
  "perfect-essence-of-the-infinite": "Совершенная сущность бесконечности",
  "soul-core-of-quipolatl": "Ядро души Киполатля",
  "soul-core-of-azcapa": "Ядро души Ацкапы",
  "soul-core-of-opiloti": "Ядро души Опилоти",
  "soul-core-of-zalatl": "Ядро души Салатля",
  "soul-core-of-cholotl": "Ядро душ Чолотля",
  "soul-core-of-tacati": "Ядро душ Такати",
  "soul-core-of-citaqualotl": "Ядро душ Ситаквалотля",
  "soul-core-of-jiquani": "Ядро душ Джиквани",
  "soul-core-of-zantipi": "Ядро душ Зантипи",
  "soul-core-of-ticaba": "Ядро душ Тикабы",
  "soul-core-of-topotante": "Ядро душ Топотанте",
  "soul-core-of-xopec": "Ядро душ Шопека",
  "soul-core-of-atmohua": "Ядро душ Атмохвы",
  "soul-core-of-tzamoto": "Ядро душ Цамото",
  "soul-core-of-puhuarte": "Ядро душ Пухварте",
  "opilotis-soul-core-of-assault": "Ядро души натиска Опилоти",
  "xopecs-soul-core-of-power": "Ядро души мощи Шопека",
  "quipolatls-soul-core-of-flow": "Ядро душ потока Квиполатля",
  "tzamotos-soul-core-of-ferocity": "Ядро душ свирепости Цамото",
  "guatelitzis-soul-core-of-endurance": "Ядро душ выносливости Гвателитзи",
  "estazuntis-soul-core-of-convalescence": "Ядро душ оздоровления Эстазунти",
  "xipocados-soul-core-of-dominion": "Ядро душ господства Шипокадо",
  "tacatis-soul-core-of-affliction": "Ядро душ недуга Такати",
  "hayoxis-soul-core-of-heatproofing": "Ядро душ жаростойкости Хайоши",
  "atmohuas-soul-core-of-retreat": "Ядро душ отступления Атмохвы",
  "cholotls-soul-core-of-war": "Ядро душ войны Чолотля",
  "citaqualotls-soul-core-of-foulness": "Ядро душ гнусности Ситаквалотля",
  "topotantes-soul-core-of-dampening": "Ядро душ подавления Топотанте",
  "uromotis-soul-core-of-attenuation": "Ядро душ истощения Уромоти",
  "zalatls-soul-core-of-insulation": "Ядро душ изоляции Залатля",
  "aldurs-saga": "Сага Альдура",
  "olroths-conviction": "Сага Олрота",
  "rigwalds-ferocity": "Свирепость Ригвальда",
  "voranas-siege": "Сага Вораны",
  "expedition-logbook": "Журнал экспедиции",
  "broken-circle-artifact": "Артефакт Разомкнутого круга",
  "black-scythe-artifact": "Артефакт Чёрной косы",
  "order-artifact": "Артефакт Ордена",
  "sun-artifact": "Артефакт Солнца",
  "olroths-crest-of-the-sun": "Знак Солнца Олрота",
  "medveds-crest-of-the-circle": "Знак Круга Медведя",
  "voranas-crest-of-the-scythe": "Знак Косы Вораны",
  "the-runebinders-alloy": "Сплав Повелителя рун",
  "the-runefathers-alloy": "Сплав Рунного отца",
  "omen-of-whittling": "Предзнаменование оттачивания",
  "omen-of-chance": "Предзнаменование удачи",
  "omen-of-light": "Предзнаменование света",
  "omen-of-abyssal-echoes": "Предзнаменование отголосков Бездны",
  "omen-of-amelioration": "Предзнаменование избавления",
  "omen-of-sinistral-erasure": "Предзнаменование истирания левши",
  "omen-of-sinistral-annulment": "Предзнаменование очищения левши",
  "omen-of-dextral-annulment": "Предзнаменование очищения правши",
  "omen-of-dextral-erasure": "Предзнаменование истирания правши",
  "omen-of-sinistral-crystallisation": "Предзнаменование кристаллизации левши",
  "omen-of-dextral-crystallisation": "Предзнаменование кристаллизации правши",
  "omen-of-sinistral-exaltation": "Предзнаменование возвышения левши",
  "omen-of-greater-exaltation": "Предзнаменование великого возвышения",
  "omen-of-sanctification": "Предзнаменование освящения",
  "omen-of-the-blessed": "Предзнаменование благодатных",
  "omen-of-catalysing-exaltation": "Предзнаменование катализованного возвышения",
  "omen-of-the-hunt": "Предзнаменование охоты",
  "omen-of-secret-compartments": "Предзнаменование тайных отсеков",
  "omen-of-reinforcements": "Предзнаменование подкреплений",
  "omen-of-answered-prayers": "Предзнаменование услышанных молитв",
  "omen-of-the-ancients": "Предзнаменование древних",
  "omen-of-chaotic-quantity": "Предзнаменование хаотичного количества",
  "omen-of-chaotic-monsters": "Предзнаменование хаотичных монстров",
  "omen-of-chaotic-rarity": "Предзнаменование хаотичной редкости",
  "omen-of-chaotic-effectiveness": "Предзнаменование хаотичной эффективности",
  "omen-of-sinistral-necromancy": "Предзнаменование некромантии левши",
  "omen-of-the-blackblooded": "Предзнаменование чернокровных",
  "omen-of-putrefaction": "Предзнаменование разложения",
  "omen-of-bartering": "Предзнаменование бартера",
  "omen-of-corruption": "Предзнаменование осквернения",
  "omen-of-dextral-alchemy": "Предзнаменование алхимии правши",
  "omen-of-dextral-coronation": "Предзнаменование коронации правши",
  "omen-of-dextral-exaltation": "Предзнаменование возвышения правши",
  "omen-of-dextral-necromancy": "Предзнаменование некромантии правши",
  "omen-of-gambling": "Предзнаменование азарта",
  "omen-of-greater-annulment": "Предзнаменование великого очищения",
  "omen-of-homogenising-coronation": "Предзнаменование единой коронации",
  "omen-of-homogenising-exaltation": "Предзнаменование единого возвышения",
  "omen-of-recombination": "Предзнаменование рекомбинации",
  "omen-of-refreshment": "Предзнаменование восполнения",
  "omen-of-resurgence": "Предзнаменование возрождения",
  "omen-of-sinistral-alchemy": "Предзнаменование алхимии левши",
  "omen-of-sinistral-coronation": "Предзнаменование коронации левши",
  "omen-of-the-liege": "Предзнаменование властителя",
  "omen-of-the-sovereign": "Предзнаменование правителя",
  "twilight-reliquary-key": "Сумеречный ключ реликвария",
  "the-arbiters-reliquary-key": "Ключ реликвария Арбитра",
  "xeshts-reliquary-key": "Ключ реликвария Кшета",
  "ritualistic-reliquary-key": "Ритуалистический ключ реликвария",
  "olroths-reliquary-key": "Ключ реликвария Олрота",
  "the-trialmasters-reliquary-key": "Ключ реликвария Мастера испытаний",
  "against-the-darkness": "Ключ от Реликвария Зарока: Противление тьме",
  "tangmazus-reliquary-key": "Ключ реликвария Тангмазу",
  "temporalis": "Ключ от Реликвария Зарока: Темпоралис",
  "uul-netols-embrace": "Объятие Уул-Нетола",
  "xophs-blood": "Кровь Ксофа",
  "tul-fall": "Падение Тул",
  "eshs-breach": "Разлом Иш",
  "chayulas-breach": "Разлом Чаюлы",
  "splinter-of-uul-netol": "Осколок Уул-Нетола",
  "splinter-of-xoph": "Осколок Ксофа",
  "splinter-of-tul": "Осколок Тул",
  "splinter-of-esh": "Осколок Иш",
  "splinter-of-chayula": "Осколок Чаюлы",
  "breachstone-of-uul-netol": "Камень Разлома Уул-Нетола",
  "breachstone-of-xoph": "Камень Разлома Ксофа",
  "breachstone-of-tul": "Камень Разлома Тул",
  "breachstone-of-esh": "Камень Разлома Иш",
  "breachstone-of-chayula": "Камень Разлома Чаюлы",
  "rakiatas-flow": "Поток Ракиаты",
  "garukhans-resolve": "Решимость Гарухан",
  "gnawed-jawbone": "Обглоданная челюсть",
  "gnawed-rib": "Обглоданное ребро",
  "gnawed-collarbone": "Обглоданная ключица",
  "mark-of-the-abyssal-lord": "Знак повелителя Бездны",
  "uncut-skill-gem": "Неогранённый камень умения",
  "uncut-support-gem": "Неогранённый камень поддержки",
  "uncut-spirit-gem": "Неогранённый камень духа",
  "lineage-lifetap": "Кровопускание Аталуи",
  "lineage-omnicurse": "Пагуба Доэдре",
  "lineage-unbound-malice": "Мука Ишчейла",
  "diluted-liquid-ire": "Разбавленный жидкий гнев",
  "diluted-liquid-guilt": "Разбавленная жидкая вина",
  "diluted-liquid-greed": "Разбавленная жидкая жадность",
  "liquid-paranoia": "Жидкая паранойя",
  "liquid-envy": "Жидкая зависть",
  "liquid-disgust": "Жидкое отвращение",
  "liquid-despair": "Жидкое отчаяние",
  "concentrated-liquid-fear": "Концентрированный жидкий страх",
  "concentrated-liquid-suffering": "Концентрированное жидкое страдание",
  "concentrated-liquid-isolation": "Концентрированное жидкое отчуждение",
  "potent-liquid-contempt": "Густое жидкое презрение",
  "potent-liquid-ferocity": "Густая жидкая свирепость",
  "potent-liquid-melancholy": "Густая жидкая меланхолия",
  "ancient-potent-liquid-contempt": "Древнее густое жидкое презрение",
  "ancient-potent-liquid-ferocity": "Древняя густая жидкая свирепость",
  "ancient-potent-liquid-melancholy": "Древняя густая жидкая меланхолия",
  "ancient-concentrated-liquid-isolation": "Древнее концентрированное жидкое отчуждение",
  "ancient-concentrated-liquid-fear": "Древний концентрированный жидкий страх",
  "ancient-concentrated-liquid-suffering": "Древнее концентрированное жидкое страдание",
  "ancient-liquid-despair": "Древнее жидкое отчаяние",
  "ancient-liquid-disgust": "Древнее жидкое отвращение",
  "ancient-liquid-paranoia": "Древняя жидкая паранойя",
  "ancient-liquid-envy": "Древняя жидкая зависть",
  "ancient-diluted-liquid-greed": "Древняя разбавленная жидкая жадность",
  "ancient-diluted-liquid-guilt": "Древняя разбавленная жидкая вина",
  "ancient-diluted-liquid-ire": "Древний разбавленный жидкий гнев",
  "call-of-the-shadows": "Зов теней",
  "vaal-cultivation-orb": "Культивирующая сфера ваал",
  "vaal-armourers-infuser": "Нагнетатель бронника ваал",
  "vaal-blacksmiths-infuser": "Нагнетатель кузнеца ваал",
  "vaal-arcanists-infuser": "Нагнетатель чародея ваал",
  "vaal-catalysing-infuser": "Катализирующий нагнетатель ваал",
  "fox-idol": "Идол лисы",
  "rabbit-idol": "Идол кролика",
  "wolf-idol": "Идол волка",
  "ox-idol": "Идол быка",
  "bear-idol": "Идол медведя",
  "boar-idol": "Идол кабана",
  "owl-idol": "Идол совы",
  "cat-idol": "Идол кошки",
  "stag-idol": "Идол оленя",
  "primate-idol": "Идол примата",
  "idol-of-ralakesh": "Идол Ралакеша",
  "idol-of-sirrius": "Идол Сирриуса",
  "idol-of-eramir": "Идол Эрамира",
  "idol-of-eeshta": "Идол Ишты",
  "idol-of-grold": "Идол Грольда",
  "idol-of-thruldana": "Идол Трулданы",
  "idol-of-egrin": "Идол Эгрина",
  "idol-of-maxarius": "Идол Макерия",
  "hawk-idol": "Идол ястреба",
  "panther-idol": "Идол пантеры",
  "snake-idol": "Идол змеи",
  "stoat-idol": "Идол горностая",
  "idol-of-alira": "Идол Алиры",
  "idol-of-greust": "Идол Груста",
  "idol-of-kraityn": "Идол Крайтина",
  "idol-of-oak": "Идол Дуба",
  "idol-of-silk": "Идол Шёлка",
  "idol-of-yeena": "Идол Йины",
  "idol-of-the-martyr": "Идол жертвы",
  "idol-of-the-pharisee": "Идол фарисея",
  "idol-of-the-sycophant": "Идол прислужника",
  "idolatry": "Идолопоклонство",
  "verisium": "Веризий",
  "exceptional-verisium": "Исключительный веризий",
  "xophs-catalyst": "Катализатор Ксофа",
  "eshs-catalyst": "Катализатор Иш",
  "tuls-catalyst": "Катализатор Тул",
  "chayulas-catalyst": "Катализатор Чаюлы",
  "adaptive-catalyst": "Адаптивный катализатор",
  "carapace-catalyst": "Панцирный катализатор",
  "flesh-catalyst": "Плотский катализатор",
  "neural-catalyst": "Невральный катализатор",
  "reaver-catalyst": "Разбойничий катализатор",
  "sibilant-catalyst": "Свистящий катализатор",
  "skittering-catalyst": "Шуршащий катализатор",
  "refined-adaptive-catalyst": "Очищенный адаптивный катализатор",
  "refined-carapace-catalyst": "Очищенный панцирный катализатор",
  "refined-chayulas-catalyst": "Очищенный катализатор Чаюлы",
  "refined-eshs-catalyst": "Очищенный катализатор Иш",
  "refined-flesh-catalyst": "Очищенный плотский катализатор",
  "refined-neural-catalyst": "Очищенный невральный катализатор",
  "refined-reaver-catalyst": "Очищенный разбойничий катализатор",
  "refined-sibilant-catalyst": "Очищенный свистящий катализатор",
  "refined-skittering-catalyst": "Очищенный шуршащий катализатор",
  "refined-tuls-catalyst": "Очищенный катализатор Тул",
  "refined-xophs-catalyst": "Очищенный катализатор Ксофа",
};

// ---------------------------------------------------------------------------
// api_id → English name (offline fallback)
// ---------------------------------------------------------------------------

const CURRENCY_NAMES_EN: Record<string, string> = {
  "exalted": "Exalted Orb",
  "chaos": "Chaos Orb",
  "divine": "Divine Orb",
  "vaal": "Vaal Orb",
  "mirror": "Mirror of Kalandra",
  "alch": "Orb of Alchemy",
  "transmute": "Orb of Transmutation",
  "aug": "Orb of Augmentation",
  "chance": "Orb of Chance",
  "annul": "Orb of Annulment",
  "regal": "Regal Orb",
  "whetstone": "Blacksmith\'s Whetstone",
  "scrap": "Armourer\'s Scrap",
  "bauble": "Glassblower\'s Bauble",
  "gcp": "Gemcutter\'s Prism",
  "etcher": "Arcanist\'s Etcher",
  "artificers": "Artificer\'s Orb",
  "wisdom": "Scroll of Wisdom",
  "fracturing-orb": "Fracturing Orb",
  "chance-shard": "Chance Shard",
  "regal-shard": "Regal Shard",
  "artificers-shard": "Artificer\'s Shard",
  "transmutation-shard": "Transmutation Shard",
  "greater-chaos-orb": "Greater Chaos Orb",
  "greater-exalted-orb": "Greater Exalted Orb",
  "greater-orb-of-transmutation": "Greater Orb of Transmutation",
  "greater-orb-of-augmentation": "Greater Orb of Augmentation",
  "greater-regal-orb": "Greater Regal Orb",
  "greater-jewellers-orb": "Greater Jeweller\'s Orb",
  "lesser-jewellers-orb": "Lesser Jeweller\'s Orb",
  "perfect-chaos-orb": "Perfect Chaos Orb",
  "perfect-exalted-orb": "Perfect Exalted Orb",
  "perfect-jewellers-orb": "Perfect Jeweller\'s Orb",
  "perfect-orb-of-transmutation": "Perfect Orb of Transmutation",
  "perfect-orb-of-augmentation": "Perfect Orb of Augmentation",
  "perfect-regal-orb": "Perfect Regal Orb",
  "cryptic-key": "Cryptic Key",
  "hinekoras-lock": "Hinekora\'s Lock",
  "portal": "Portal Scroll",
  "identify": "Scroll of Identification",
  "scouring": "Orb of Scouring",
  "regret": "Orb of Regret",
  "fusings": "Orb of Fusing",
  "chromatic": "Chromatic Orb",
  "jeweller": "Jeweller\'s Orb",
  "blessed": "Blessed Orb",
  "eternal": "Eternal Orb",
  "silver": "Silver Coin",
  "gold": "Gold",
  "perandus": "Perandus Coin",
  "alteration": "Orb of Alteration",
  "raven-touched-shard": "Raven-Touched Shard",
  "head-of-the-king": "Head of the King",
  "astrids-creativity": "Astrid's Creativity",
  // NOTE: PoE2 runes overhauled — fire/ice/lightning tiers removed.
  "essence-of-horror": "Essence of Horror",
  "essence-of-delirium": "Essence of Delirium",
  "essence-of-hysteria": "Essence of Hysteria",
  "essence-of-insanity": "Essence of Insanity",
  "essence-of-ice": "Essence of Ice",
  "essence-of-flames": "Essence of Flames",
  "essence-of-the-mind": "Essence of the Mind",
  "essence-of-the-body": "Essence of the Body",
  "essence-of-opulence": "Essence of Opulence",
  "essence-of-ruin": "Essence of Ruin",
  "essence-of-battle": "Essence of Battle",
  "essence-of-sorcery": "Essence of Sorcery",
  "essence-of-alacrity": "Essence of Alacrity",
  "essence-of-command": "Essence of Command",
  "essence-of-enhancement": "Essence of Enhancement",
  "essence-of-electricity": "Essence of Electricity",
  "essence-of-grounding": "Essence of Grounding",
  "essence-of-haste": "Essence of Haste",
  "essence-of-insulation": "Essence of Insulation",
  "essence-of-seeking": "Essence of Seeking",
  "essence-of-thawing": "Essence of Thawing",
  "essence-of-abrasion": "Essence of Abrasion",
  "essence-of-the-abyss": "Essence of the Abyss",
  "essence-of-the-breach": "Essence of the Breach",
  "essence-of-the-infinite": "Essence of the Infinite",
  "greater-essence-of-ice": "Greater Essence of Ice",
  "greater-essence-of-flames": "Greater Essence of Flames",
  "greater-essence-of-the-mind": "Greater Essence of the Mind",
  "greater-essence-of-the-body": "Greater Essence of the Body",
  "greater-essence-of-opulence": "Greater Essence of Opulence",
  "greater-essence-of-ruin": "Greater Essence of Ruin",
  "greater-essence-of-battle": "Greater Essence of Battle",
  "greater-essence-of-sorcery": "Greater Essence of Sorcery",
  "greater-essence-of-alacrity": "Greater Essence of Alacrity",
  "greater-essence-of-command": "Greater Essence of Command",
  "greater-essence-of-enhancement": "Greater Essence of Enhancement",
  "greater-essence-of-electricity": "Greater Essence of Electricity",
  "greater-essence-of-grounding": "Greater Essence of Grounding",
  "greater-essence-of-haste": "Greater Essence of Haste",
  "greater-essence-of-insulation": "Greater Essence of Insulation",
  "greater-essence-of-seeking": "Greater Essence of Seeking",
  "greater-essence-of-thawing": "Greater Essence of Thawing",
  "greater-essence-of-abrasion": "Greater Essence of Abrasion",
  "greater-essence-of-the-infinite": "Greater Essence of the Infinite",
  "lesser-essence-of-ice": "Lesser Essence of Ice",
  "lesser-essence-of-flames": "Lesser Essence of Flames",
  "lesser-essence-of-the-mind": "Lesser Essence of the Mind",
  "lesser-essence-of-the-body": "Lesser Essence of the Body",
  "lesser-essence-of-opulence": "Lesser Essence of Opulence",
  "lesser-essence-of-ruin": "Lesser Essence of Ruin",
  "lesser-essence-of-battle": "Lesser Essence of Battle",
  "lesser-essence-of-sorcery": "Lesser Essence of Sorcery",
  "lesser-essence-of-alacrity": "Lesser Essence of Alacrity",
  "lesser-essence-of-command": "Lesser Essence of Command",
  "lesser-essence-of-enhancement": "Lesser Essence of Enhancement",
  "lesser-essence-of-electricity": "Lesser Essence of Electricity",
  "lesser-essence-of-grounding": "Lesser Essence of Grounding",
  "lesser-essence-of-haste": "Lesser Essence of Haste",
  "lesser-essence-of-insulation": "Lesser Essence of Insulation",
  "lesser-essence-of-seeking": "Lesser Essence of Seeking",
  "lesser-essence-of-thawing": "Lesser Essence of Thawing",
  "lesser-essence-of-abrasion": "Lesser Essence of Abrasion",
  "lesser-essence-of-the-infinite": "Lesser Essence of the Infinite",
  "perfect-essence-of-ice": "Perfect Essence of Ice",
  "perfect-essence-of-flames": "Perfect Essence of Flames",
  "perfect-essence-of-the-mind": "Perfect Essence of the Mind",
  "perfect-essence-of-the-body": "Perfect Essence of the Body",
  "perfect-essence-of-opulence": "Perfect Essence of Opulence",
  "perfect-essence-of-ruin": "Perfect Essence of Ruin",
  "perfect-essence-of-battle": "Perfect Essence of Battle",
  "perfect-essence-of-sorcery": "Perfect Essence of Sorcery",
  "perfect-essence-of-alacrity": "Perfect Essence of Alacrity",
  "perfect-essence-of-command": "Perfect Essence of Command",
  "perfect-essence-of-enhancement": "Perfect Essence of Enhancement",
  "perfect-essence-of-electricity": "Perfect Essence of Electricity",
  "perfect-essence-of-grounding": "Perfect Essence of Grounding",
  "perfect-essence-of-haste": "Perfect Essence of Haste",
  "perfect-essence-of-insulation": "Perfect Essence of Insulation",
  "perfect-essence-of-seeking": "Perfect Essence of Seeking",
  "perfect-essence-of-thawing": "Perfect Essence of Thawing",
  "perfect-essence-of-abrasion": "Perfect Essence of Abrasion",
  "perfect-essence-of-the-infinite": "Perfect Essence of the Infinite",
  "soul-core-of-quipolatl": "Soul Core of Quipolatl",
  "soul-core-of-azcapa": "Soul Core of Azcapa",
  "soul-core-of-opiloti": "Soul Core of Opiloti",
  "soul-core-of-zalatl": "Soul Core of Zalatl",
  "soul-core-of-cholotl": "Soul Core of Cholotl",
  "soul-core-of-tacati": "Soul Core of Tacati",
  "soul-core-of-citaqualotl": "Soul Core of Citaqualotl",
  "soul-core-of-jiquani": "Soul Core of Jiquani",
  "soul-core-of-zantipi": "Soul Core of Zantipi",
  "soul-core-of-ticaba": "Soul Core of Ticaba",
  "soul-core-of-topotante": "Soul Core of Topotante",
  "soul-core-of-xopec": "Soul Core of Xopec",
  "soul-core-of-atmohua": "Soul Core of Atmohua",
  "soul-core-of-tzamoto": "Soul Core of Tzamoto",
  "soul-core-of-puhuarte": "Soul Core of Puhuarte",
  "opilotis-soul-core-of-assault": "Opiloti\'s Soul Core of Assault",
  "xopecs-soul-core-of-power": "Xopec\'s Soul Core of Power",
  "quipolatls-soul-core-of-flow": "Quipolatl\'s Soul Core of Flow",
  "tzamotos-soul-core-of-ferocity": "Tzamoto\'s Soul Core of Ferocity",
  "guatelitzis-soul-core-of-endurance": "Guatelitzi\'s Soul Core of Endurance",
  "estazuntis-soul-core-of-convalescence": "Estazunti\'s Soul Core of Convalescence",
  "xipocados-soul-core-of-dominion": "Xipocado\'s Soul Core of Dominion",
  "tacatis-soul-core-of-affliction": "Tacati\'s Soul Core of Affliction",
  "hayoxis-soul-core-of-heatproofing": "Hayoxi\'s Soul Core of Heatproofing",
  "atmohuas-soul-core-of-retreat": "Atmohua\'s Soul Core of Retreat",
  "cholotls-soul-core-of-war": "Cholotl\'s Soul Core of War",
  "citaqualotls-soul-core-of-foulness": "Citaqualotl\'s Soul Core of Foulness",
  "topotantes-soul-core-of-dampening": "Topotante\'s Soul Core of Dampening",
  "uromotis-soul-core-of-attenuation": "Uromoti\'s Soul Core of Attenuation",
  "zalatls-soul-core-of-insulation": "Zalatl\'s Soul Core of Insulation",
  "aldurs-saga": "Aldur\'s Saga",
  "olroths-conviction": "Olroth\'s Conviction",
  "rigwalds-ferocity": "Rigwald\'s Ferocity",
  "voranas-siege": "Vorana\'s Siege",
  "expedition-logbook": "Expedition Logbook",
  "broken-circle-artifact": "Broken Circle Artifact",
  "black-scythe-artifact": "Black Scythe Artifact",
  "order-artifact": "Order Artifact",
  "sun-artifact": "Sun Artifact",
  "olroths-crest-of-the-sun": "Olroth\'s Crest of the Sun",
  "medveds-crest-of-the-circle": "Medved\'s Crest of the Circle",
  "voranas-crest-of-the-scythe": "Vorana\'s Crest of the Scythe",
  "the-runebinders-alloy": "The Runebinder\'s Alloy",
  "the-runefathers-alloy": "The Runefather\'s Alloy",
  "omen-of-whittling": "Omen of Whittling",
  "omen-of-chance": "Omen of Chance",
  "omen-of-light": "Omen of Light",
  "omen-of-abyssal-echoes": "Omen of Abyssal Echoes",
  "omen-of-amelioration": "Omen of Amelioration",
  "omen-of-sinistral-erasure": "Omen of Sinistral Erasure",
  "omen-of-sinistral-annulment": "Omen of Sinistral Annulment",
  "omen-of-dextral-annulment": "Omen of Dextral Annulment",
  "omen-of-dextral-erasure": "Omen of Dextral Erasure",
  "omen-of-sinistral-crystallisation": "Omen of Sinistral Crystallisation",
  "omen-of-dextral-crystallisation": "Omen of Dextral Crystallisation",
  "omen-of-sinistral-exaltation": "Omen of Sinistral Exaltation",
  "omen-of-greater-exaltation": "Omen of Greater Exaltation",
  "omen-of-sanctification": "Omen of Sanctification",
  "omen-of-the-blessed": "Omen of the Blessed",
  "omen-of-catalysing-exaltation": "Omen of Catalysing Exaltation",
  "omen-of-the-hunt": "Omen of the Hunt",
  "omen-of-secret-compartments": "Omen of Secret Compartments",
  "omen-of-reinforcements": "Omen of Reinforcements",
  "omen-of-answered-prayers": "Omen of Answered Prayers",
  "omen-of-the-ancients": "Omen of the Ancients",
  "omen-of-chaotic-quantity": "Omen of Chaotic Quantity",
  "omen-of-chaotic-monsters": "Omen of Chaotic Monsters",
  "omen-of-chaotic-rarity": "Omen of Chaotic Rarity",
  "omen-of-chaotic-effectiveness": "Omen of Chaotic Effectiveness",
  "omen-of-sinistral-necromancy": "Omen of Sinistral Necromancy",
  "omen-of-the-blackblooded": "Omen of the Blackblooded",
  "omen-of-putrefaction": "Omen of Putrefaction",
  "omen-of-bartering": "Omen of Bartering",
  "omen-of-corruption": "Omen of Corruption",
  "omen-of-dextral-alchemy": "Omen of Dextral Alchemy",
  "omen-of-dextral-coronation": "Omen of Dextral Coronation",
  "omen-of-dextral-exaltation": "Omen of Dextral Exaltation",
  "omen-of-dextral-necromancy": "Omen of Dextral Necromancy",
  "omen-of-gambling": "Omen of Gambling",
  "omen-of-greater-annulment": "Omen of Greater Annulment",
  "omen-of-homogenising-coronation": "Omen of Homogenising Coronation",
  "omen-of-homogenising-exaltation": "Omen of Homogenising Exaltation",
  "omen-of-recombination": "Omen of Recombination",
  "omen-of-refreshment": "Omen of Refreshment",
  "omen-of-resurgence": "Omen of Resurgence",
  "omen-of-sinistral-alchemy": "Omen of Sinistral Alchemy",
  "omen-of-sinistral-coronation": "Omen of Sinistral Coronation",
  "omen-of-the-liege": "Omen of the Liege",
  "omen-of-the-sovereign": "Omen of the Sovereign",
  "twilight-reliquary-key": "Twilight Reliquary Key",
  "the-arbiters-reliquary-key": "The Arbiter\'s Reliquary Key",
  "xeshts-reliquary-key": "Xesht\'s Reliquary Key",
  "ritualistic-reliquary-key": "Ritualistic Reliquary Key",
  "olroths-reliquary-key": "Olroth\'s Reliquary Key",
  "the-trialmasters-reliquary-key": "The Trialmaster\'s Reliquary Key",
  "against-the-darkness": "Against the Darkness",
  "tangmazus-reliquary-key": "Tangmazu\'s Reliquary Key",
  "temporalis": "Zarokh\'s Reliquary Key: Temporalis",
  "uul-netols-embrace": "Uul-Netol\'s Embrace",
  "xophs-blood": "Xoph\'s Blood",
  "tul-fall": "Tul\'s Fall",
  "eshs-breach": "Esh\'s Breach",
  "chayulas-breach": "Chayula\'s Breach",
  "splinter-of-uul-netol": "Splinter of Uul-Netol",
  "splinter-of-xoph": "Splinter of Xoph",
  "splinter-of-tul": "Splinter of Tul",
  "splinter-of-esh": "Splinter of Esh",
  "splinter-of-chayula": "Splinter of Chayula",
  "breachstone-of-uul-netol": "Breachstone of Uul-Netol",
  "breachstone-of-xoph": "Breachstone of Xoph",
  "breachstone-of-tul": "Breachstone of Tul",
  "breachstone-of-esh": "Breachstone of Esh",
  "breachstone-of-chayula": "Breachstone of Chayula",
  "rakiatas-flow": "Rakiata\'s Flow",
  "garukhans-resolve": "Garukhan\'s Resolve",
  "gnawed-jawbone": "Gnawed Jawbone",
  "gnawed-rib": "Gnawed Rib",
  "gnawed-collarbone": "Gnawed Collarbone",
  "mark-of-the-abyssal-lord": "Mark of the Abyssal Lord",
  "uncut-skill-gem": "Uncut Skill Gem",
  "uncut-support-gem": "Uncut Support Gem",
  "uncut-spirit-gem": "Uncut Spirit Gem",
  "lineage-lifetap": "Lineage: Lifetap",
  "lineage-omnicurse": "Lineage: Omnicurse",
  "lineage-unbound-malice": "Lineage: Unbound Malice",
  "diluted-liquid-ire": "Diluted Liquid Ire",
  "diluted-liquid-guilt": "Diluted Liquid Guilt",
  "diluted-liquid-greed": "Diluted Liquid Greed",
  "liquid-paranoia": "Liquid Paranoia",
  "liquid-envy": "Liquid Envy",
  "liquid-disgust": "Liquid Disgust",
  "liquid-despair": "Liquid Despair",
  "concentrated-liquid-fear": "Concentrated Liquid Fear",
  "concentrated-liquid-suffering": "Concentrated Liquid Suffering",
  "concentrated-liquid-isolation": "Concentrated Liquid Isolation",
  "potent-liquid-contempt": "Potent Liquid Contempt",
  "potent-liquid-ferocity": "Potent Liquid Ferocity",
  "potent-liquid-melancholy": "Potent Liquid Melancholy",
  "ancient-potent-liquid-contempt": "Ancient Potent Liquid Contempt",
  "ancient-potent-liquid-ferocity": "Ancient Potent Liquid Ferocity",
  "ancient-potent-liquid-melancholy": "Ancient Potent Liquid Melancholy",
  "ancient-concentrated-liquid-isolation": "Ancient Concentrated Liquid Isolation",
  "ancient-concentrated-liquid-fear": "Ancient Concentrated Liquid Fear",
  "ancient-concentrated-liquid-suffering": "Ancient Concentrated Liquid Suffering",
  "ancient-liquid-despair": "Ancient Liquid Despair",
  "ancient-liquid-disgust": "Ancient Liquid Disgust",
  "ancient-liquid-paranoia": "Ancient Liquid Paranoia",
  "ancient-liquid-envy": "Ancient Liquid Envy",
  "ancient-diluted-liquid-greed": "Ancient Diluted Liquid Greed",
  "ancient-diluted-liquid-guilt": "Ancient Diluted Liquid Guilt",
  "ancient-diluted-liquid-ire": "Ancient Diluted Liquid Ire",
  "call-of-the-shadows": "Call of the Shadows",
  "vaal-cultivation-orb": "Vaal Cultivation Orb",
  "vaal-armourers-infuser": "Vaal Armourer\'s Infuser",
  "vaal-blacksmiths-infuser": "Vaal Blacksmith\'s Infuser",
  "vaal-arcanists-infuser": "Vaal Arcanist\'s Infuser",
  "vaal-catalysing-infuser": "Vaal Catalysing Infuser",
  "fox-idol": "Fox Idol",
  "rabbit-idol": "Rabbit Idol",
  "wolf-idol": "Wolf Idol",
  "ox-idol": "Ox Idol",
  "bear-idol": "Bear Idol",
  "boar-idol": "Boar Idol",
  "owl-idol": "Owl Idol",
  "cat-idol": "Cat Idol",
  "stag-idol": "Stag Idol",
  "primate-idol": "Primate Idol",
  "idol-of-ralakesh": "Idol of Ralakesh",
  "idol-of-sirrius": "Idol of Sirrius",
  "idol-of-eramir": "Idol of Eramir",
  "idol-of-eeshta": "Idol of Eeshta",
  "idol-of-grold": "Idol of Grold",
  "idol-of-thruldana": "Idol of Thruldana",
  "idol-of-egrin": "Idol of Egrin",
  "idol-of-maxarius": "Idol of Maxarius",
  "hawk-idol": "Hawk Idol",
  "panther-idol": "Panther Idol",
  "snake-idol": "Snake Idol",
  "stoat-idol": "Stoat Idol",
  "idol-of-alira": "Idol of Alira",
  "idol-of-greust": "Idol of Greust",
  "idol-of-kraityn": "Idol of Kraityn",
  "idol-of-oak": "Idol of Oak",
  "idol-of-silk": "Idol of Silk",
  "idol-of-yeena": "Idol of Yeena",
  "idol-of-the-martyr": "Idol of the Martyr",
  "idol-of-the-pharisee": "Idol of the Pharisee",
  "idol-of-the-sycophant": "Idol of the Sycophant",
  "idolatry": "Idolatry",
  "verisium": "Verisium",
  "exceptional-verisium": "Exceptional Verisium",
  // Catalysts
  "xophs-catalyst": "Xoph's Catalyst",
  "eshs-catalyst": "Esh's Catalyst",
  "tuls-catalyst": "Tul's Catalyst",
  "chayulas-catalyst": "Chayula's Catalyst",
  "adaptive-catalyst": "Adaptive Catalyst",
  "carapace-catalyst": "Carapace Catalyst",
  "flesh-catalyst": "Flesh Catalyst",
  "neural-catalyst": "Neural Catalyst",
  "reaver-catalyst": "Reaver Catalyst",
  "sibilant-catalyst": "Sibilant Catalyst",
  "skittering-catalyst": "Skittering Catalyst",
  "refined-adaptive-catalyst": "Refined Adaptive Catalyst",
  "refined-carapace-catalyst": "Refined Carapace Catalyst",
  "refined-chayulas-catalyst": "Refined Chayula's Catalyst",
  "refined-eshs-catalyst": "Refined Esh's Catalyst",
  "refined-flesh-catalyst": "Refined Flesh Catalyst",
  "refined-neural-catalyst": "Refined Neural Catalyst",
  "refined-reaver-catalyst": "Refined Reaver Catalyst",
  "refined-sibilant-catalyst": "Refined Sibilant Catalyst",
  "refined-skittering-catalyst": "Refined Skittering Catalyst",
  "refined-tuls-catalyst": "Refined Tul's Catalyst",
  "refined-xophs-catalyst": "Refined Xoph's Catalyst",
};

// ---------------------------------------------------------------------------
// Lookup functions
// ---------------------------------------------------------------------------

/**
 * Get the Russian display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyRuName(apiId: string): string | null {
  return CURRENCY_NAMES_RU[apiId] ?? CURRENCY_NAMES_RU[apiId.toLowerCase()] ?? null;
}

/**
 * Get the English display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyEnName(apiId: string): string | null {
  return CURRENCY_NAMES_EN[apiId] ?? CURRENCY_NAMES_EN[apiId.toLowerCase()] ?? null;
}

/**
 * Get a display name for a currency pair like "exalted/chaos".
 * Uses Russian names if available, falls back to api_ids.
 */
export function getCurrencyPairDisplayName(
  pairStr: string,
  locale: "ru" | "en" = "ru",
): string {
  const parts = pairStr.split("/");
  if (parts.length !== 2) return pairStr;

  const lookup = locale === "ru" ? getCurrencyRuName : getCurrencyEnName;
  const from = lookup(parts[0]) ?? parts[0];
  const to = lookup(parts[1]) ?? parts[1];
  return `${from}/${to}`;
}

