/**
 * Client-side api_id → display name mapping for PoE2 currencies and items.
 *
 * PURPOSE:
 *   When the backend is online, flip responses include `currencyFromRu` /
 *   `currencyToRu` fields from `backend/data/currency_names_ru.py`.
 *   This file provides a FALLBACK for:
 *     1. Offline mode (backend down, only cache/prepopulated data available)
 *     2. Items not yet in the backend mapping
 *     3. Currencies table, exchange table, and other non-flip views
 *
 * USAGE:
 *   import { getCurrencyRuName, getCurrencyEnName } from "@/lib/currency-names";
 *   const ruName = getCurrencyRuName("exalted"); // "Благородная сфера"
 *
 * MAINTAINER NOTES:
 *   - Auto-synced from backend/data/currency_names_ru.py (iteration 30)
 *   - Source tags (# poe2db, # poedb) are stripped in this file for cleanliness
 *   - The full backend has 404+ RU entries; this file mirrors all of them
 */

// ---------------------------------------------------------------------------
// api_id → Russian name (offline fallback)
// ---------------------------------------------------------------------------

const CURRENCY_NAMES_RU: Record<string, string> = {
  "exalted": "Благородная сфера",
  "chaos": "Сфера хаоса",
  "divine": "Божественная сфера",
  "vaal": "Сфера Ваала",
  "mirror": "Зеркало Каландры",
  "alch": "Сфера алхимика",
  "transmute": "Сфера превращения",
  "aug": "Сфера дополнения",
  "chance": "Сфера удачи",
  "annul": "Сфера аннулирования",
  "regal": "Коронованная сфера",
  "whetstone": "Точильный камень кузнеца",
  "scrap": "Кусок брони",
  "bauble": "Стеклодувная бусина",
  "gcp": "Призма резчика камней",
  "etcher": "Резец чародея",
  "artificers": "Сфера астромантии",
  "wisdom": "Свиток мудрости",
  "fracturing-orb": "Сфера раскалывания",
  "chance-shard": "Осколок удачи",
  "regal-shard": "Осколок коронованной сферы",
  "artificers-shard": "Осколок астромантии",
  "transmutation-shard": "Осколок сферы превращения",
  "greater-chaos-orb": "Большая сфера хаоса",
  "greater-exalted-orb": "Большая сфера возвышения",
  "greater-orb-of-transmutation": "Большая сфера превращения",
  "greater-orb-of-augmentation": "Большая сфера усиления",
  "greater-regal-orb": "Большая сфера царей",
  "greater-jewellers-orb": "Большая сфера златокузнеца",
  "lesser-jewellers-orb": "Малая сфера златокузнеца",
  "perfect-chaos-orb": "Совершенная сфера хаоса",
  "perfect-exalted-orb": "Совершенная сфера возвышения",
  "perfect-jewellers-orb": "Совершенная сфера златокузнеца",
  "perfect-orb-of-transmutation": "Совершенная сфера превращения",
  "perfect-orb-of-augmentation": "Совершенная сфера усиления",
  "perfect-regal-orb": "Совершенная сфера царей",
  "cryptic-key": "Скрытый ключ",
  "hinekoras-lock": "Прядь Хинекоры",
  "portal": "Свиток портала",
  "identify": "Свиток опознания",
  "scouring": "Сфера очищения",
  "regret": "Сфера сожаления",
  "fusings": "Сфера слияния",
  "chromatic": "Хроматическая сфера",
  "jeweller": "Сфера ювелира",
  "blessed": "Благословенная сфера",
  "eternal": "Вечная сфера",
  "silver": "Серебряная монета",
  "gold": "Золото",
  "perandus": "Монета Перандуса",
  "alteration": "Сфера перемен",
  "raven-touched-shard": "Осколок, тронутый вороном",
  "head-of-the-king": "Голова короля",
  "astrids-creativity": "Творчество Астрид",
  "fire-rune-tier-1": "Огненная руна I уровня",
  "fire-rune-tier-2": "Огненная руна II уровня",
  "fire-rune-tier-3": "Огненная руна III уровня",
  "ice-rune-tier-1": "Ледяная руна I уровня",
  "ice-rune-tier-2": "Ледяная руна II уровня",
  "ice-rune-tier-3": "Ледяная руна III уровня",
  "lightning-rune-tier-1": "Руны молнии I уровня",
  "lightning-rune-tier-2": "Руны молнии II уровня",
  "lightning-rune-tier-3": "Руны молнии III уровня",
  "essence-of-enfeeblement": "Сущность ослабления",
  "essence-of-sorrow": "Сущность печали",
  "essence-of-rage": "Сущность ярости",
  "essence-of-suffering": "Сущность страдания",
  "essence-of-wrath": "Сущность гнева",
  "essence-of-doubt": "Сущность сомнения",
  "essence-of-anger": "Сущность злобы",
  "essence-of-torment": "Сущность мучения",
  "essence-of-fear": "Сущность страха",
  "essence-of-horror": "Сущность ужаса",
  "essence-of-delirium": "Сущность бреда",
  "essence-of-hysteria": "Сущность истерии",
  "essence-of-insanity": "Сущность безумия",
  "essence-of-ice": "Сущность льда",
  "essence-of-flames": "Сущность пламени",
  "essence-of-the-mind": "Сущность разума",
  "essence-of-the-body": "Сущность тела",
  "essence-of-opulence": "Сущность изобилия",
  "essence-of-ruin": "Сущность гибели",
  "essence-of-battle": "Сущность битвы",
  "essence-of-sorcery": "Сущность колдовства",
  "essence-of-alacrity": "Сущность живости",
  "essence-of-command": "Сущность повеления",
  "essence-of-enhancement": "Сущность улучшения",
  "essence-of-electricity": "Сущность электричества",
  "essence-of-grounding": "Сущность заземления",
  "essence-of-haste": "Сущность спешки",
  "essence-of-insulation": "Сущность изоляции",
  "essence-of-seeking": "Сущность искания",
  "essence-of-thawing": "Сущность таяния",
  "essence-of-abrasion": "Сущность разрушения",
  "essence-of-the-abyss": "Сущность Бездны",
  "essence-of-the-breach": "Сущность Разлома",
  "essence-of-the-infinite": "Сущность бесконечности",
  "deafening-essence-of-enfeeblement": "Оглушающая сущность ослабления",
  "deafening-essence-of-sorrow": "Оглушающая сущность печали",
  "deafening-essence-of-rage": "Оглушающая сущность ярости",
  "deafening-essence-of-suffering": "Оглушающая сущность страдания",
  "deafening-essence-of-wrath": "Оглушающая сущность гнева",
  "deafening-essence-of-doubt": "Оглушающая сущность сомнения",
  "deafening-essence-of-anger": "Оглушающая сущность злобы",
  "deafening-essence-of-torment": "Оглушающая сущность мучения",
  "deafening-essence-of-fear": "Оглушающая сущность страха",
  "deafening-essence-of-horror": "Оглушающая сущность ужаса",
  "deafening-essence-of-delirium": "Оглушающая сущность бреда",
  "deafening-essence-of-hysteria": "Оглушающая сущность истерии",
  "deafening-essence-of-insanity": "Оглушающая сущность безумия",
  "life-essence": "Сущность жизни",
  "mana-essence": "Сущность маны",
  "greater-essence-of-ice": "Большая сущность льда",
  "greater-essence-of-flames": "Большая сущность пламени",
  "greater-essence-of-the-mind": "Большая сущность разума",
  "greater-essence-of-the-body": "Большая сущность тела",
  "greater-essence-of-opulence": "Большая сущность изобилия",
  "greater-essence-of-ruin": "Большая сущность гибели",
  "greater-essence-of-battle": "Большая сущность битвы",
  "greater-essence-of-sorcery": "Большая сущность колдовства",
  "greater-essence-of-alacrity": "Большая сущность живости",
  "greater-essence-of-command": "Большая сущность повеления",
  "greater-essence-of-enhancement": "Большая сущность улучшения",
  "greater-essence-of-electricity": "Большая сущность электричества",
  "greater-essence-of-grounding": "Большая сущность заземления",
  "greater-essence-of-haste": "Большая сущность спешки",
  "greater-essence-of-insulation": "Большая сущность изоляции",
  "greater-essence-of-seeking": "Большая сущность искания",
  "greater-essence-of-thawing": "Большая сущность таяния",
  "greater-essence-of-abrasion": "Большая сущность разрушения",
  "greater-essence-of-the-infinite": "Большая сущность бесконечности",
  "lesser-essence-of-ice": "Малая сущность льда",
  "lesser-essence-of-flames": "Малая сущность пламени",
  "lesser-essence-of-the-mind": "Малая сущность разума",
  "lesser-essence-of-the-body": "Малая сущность тела",
  "lesser-essence-of-opulence": "Малая сущность изобилия",
  "lesser-essence-of-ruin": "Малая сущность гибели",
  "lesser-essence-of-battle": "Малая сущность битвы",
  "lesser-essence-of-sorcery": "Малая сущность колдовства",
  "lesser-essence-of-alacrity": "Малая сущность живости",
  "lesser-essence-of-command": "Малая сущность повеления",
  "lesser-essence-of-enhancement": "Малая сущность улучшения",
  "lesser-essence-of-electricity": "Малая сущность электричества",
  "lesser-essence-of-grounding": "Малая сущность заземления",
  "lesser-essence-of-haste": "Малая сущность спешки",
  "lesser-essence-of-insulation": "Малая сущность изоляции",
  "lesser-essence-of-seeking": "Малая сущность искания",
  "lesser-essence-of-thawing": "Малая сущность таяния",
  "lesser-essence-of-abrasion": "Малая сущность разрушения",
  "lesser-essence-of-the-infinite": "Малая сущность бесконечности",
  "perfect-essence-of-ice": "Совершенная сущность льда",
  "perfect-essence-of-flames": "Совершенная сущность пламени",
  "perfect-essence-of-the-mind": "Совершенная сущность разума",
  "perfect-essence-of-the-body": "Совершенная сущность тела",
  "perfect-essence-of-opulence": "Совершенная сущность изобилия",
  "perfect-essence-of-ruin": "Совершенная сущность гибели",
  "perfect-essence-of-battle": "Совершенная сущность битвы",
  "perfect-essence-of-sorcery": "Совершенная сущность колдовства",
  "perfect-essence-of-alacrity": "Совершенная сущность живости",
  "perfect-essence-of-command": "Совершенная сущность повеления",
  "perfect-essence-of-enhancement": "Совершенная сущность улучшения",
  "perfect-essence-of-electricity": "Совершенная сущность электричества",
  "perfect-essence-of-grounding": "Совершенная сущность заземления",
  "perfect-essence-of-haste": "Совершенная сущность спешки",
  "perfect-essence-of-insulation": "Совершенная сущность изоляции",
  "perfect-essence-of-seeking": "Совершенная сущность искания",
  "perfect-essence-of-thawing": "Совершенная сущность таяния",
  "perfect-essence-of-abrasion": "Совершенная сущность разрушения",
  "perfect-essence-of-the-infinite": "Совершенная сущность бесконечности",
  "soul-core-of-quipolatl": "Ядро души Киполатля",
  "soul-core-of-azcapa": "Ядро души Ацкапы",
  "soul-core-of-opiloti": "Ядро души Опилоти",
  "soul-core-of-zalatl": "Ядро души Салатля",
  "soul-core-of-cholotl": "Ядро душ Чолотля",
  "soul-core-of-tacati": "Ядро душ Такати",
  "soul-core-of-citaqualotl": "Ядро душ Ситаквалотля",
  "soul-core-of-jiquani": "Ядро душ Джиквани",
  "soul-core-of-zantipi": "Ядро душ Зантипи",
  "soul-core-of-ticaba": "Ядро душ Тикабы",
  "soul-core-of-topotante": "Ядро душ Топотанте",
  "soul-core-of-xopec": "Ядро душ Шопека",
  "soul-core-of-atmohua": "Ядро душ Атмохвы",
  "soul-core-of-tzamoto": "Ядро душ Цамото",
  "soul-core-of-puhuarte": "Ядро душ Пухварте",
  "opilotis-soul-core-of-assault": "Ядро души натиска Опилоти",
  "xopecs-soul-core-of-power": "Ядро души мощи Шопека",
  "quipolatls-soul-core-of-flow": "Ядро душ потока Квиполатля",
  "tzamotos-soul-core-of-ferocity": "Ядро душ свирепости Цамото",
  "guatelitzis-soul-core-of-endurance": "Ядро душ выносливости Гвателитзи",
  "estazuntis-soul-core-of-convalescence": "Ядро душ оздоровления Эстазунти",
  "xipocados-soul-core-of-dominion": "Ядро душ господства Шипокадо",
  "tacatis-soul-core-of-affliction": "Ядро душ недуга Такати",
  "hayoxis-soul-core-of-heatproofing": "Ядро душ жаростойкости Хайоши",
  "atmohuas-soul-core-of-retreat": "Ядро душ отступления Атмохвы",
  "cholotls-soul-core-of-war": "Ядро душ войны Чолотля",
  "citaqualotls-soul-core-of-foulness": "Ядро душ гнусности Ситаквалотля",
  "topotantes-soul-core-of-dampening": "Ядро душ подавления Топотанте",
  "uromotis-soul-core-of-attenuation": "Ядро душ истощения Уромоти",
  "zalatls-soul-core-of-insulation": "Ядро душ изоляции Залатля",
  "aldurs-saga": "Сага Альдура",
  "olroths-conviction": "Сага Олрота",
  "rigwalds-ferocity": "Свирепость Ригвальда",
  "voranas-siege": "Сага Вораны",
  "gwenithas-gamble": "Азарт Гвенифы",
  "medveds-might": "Мощь Медведя",
  "tujen-penny": "Пенни Туджена",
  "rostas-faith": "Вера Росты",
  "ursas-resolution": "Решимость Урсы",
  "sukaas-dash": "Рывок Сукаа",
  "dannigs-honour": "Честь Даннига",
  "kalguur-rune": "Руна Калгура",
  "expedition-logbook": "Журнал экспедиции",
  "artifact-of-the-chayula": "Артефакт Чаюлы",
  "artifact-of-the-vaal": "Артефакт Ваала",
  "artifact-of-the-abyss": "Артефакт Бездны",
  "artifact-of-the-breach": "Артефакт Разлома",
  "sun-touched-helmet": "Солнцеликый шлем",
  "sun-touched-armour": "Солнцеликый доспех",
  "sun-touched-gloves": "Солнцеликые перчатки",
  "sun-touched-boots": "Солнцеликые сапоги",
  "sun-touched-weapon": "Солнцеликое оружие",
  "omen-of-whittling": "Предзнаменование оттачивания",
  "omen-of-chance": "Предзнаменование удачи",
  "omen-of-light": "Предзнаменование света",
  "omen-of-abyssal-echoes": "Предзнаменование отголосков Бездны",
  "omen-of-amelioration": "Предзнаменование избавления",
  "omen-of-sinistral-erasure": "Предзнаменование истирания левши",
  "omen-of-sinistral-annulment": "Предзнаменование очищения левши",
  "omen-of-dextral-annulment": "Предзнаменование очищения правши",
  "omen-of-dextral-erasure": "Предзнаменование истирания правши",
  "omen-of-sinistral-crystallisation": "Предзнаменование кристаллизации левши",
  "omen-of-dextral-crystallisation": "Предзнаменование кристаллизации правши",
  "omen-of-sinistral-exaltation": "Предзнаменование возвышения левши",
  "omen-of-greater-exaltation": "Предзнаменование великого возвышения",
  "omen-of-sanctification": "Предзнаменование освящения",
  "omen-of-the-blessed": "Предзнаменование благодатных",
  "omen-of-catalysing-exaltation": "Предзнаменование катализованного возвышения",
  "omen-of-the-hunt": "Предзнаменование охоты",
  "omen-of-secret-compartments": "Предзнаменование тайных отсеков",
  "omen-of-reinforcements": "Предзнаменование подкреплений",
  "omen-of-answered-prayers": "Предзнаменование услышанных молитв",
  "omen-of-the-ancients": "Предзнаменование древних",
  "omen-of-chaotic-quantity": "Предзнаменование хаотичного количества",
  "omen-of-chaotic-monsters": "Предзнаменование хаотичных монстров",
  "omen-of-chaotic-rarity": "Предзнаменование хаотичной редкости",
  "omen-of-chaotic-effectiveness": "Предзнаменование хаотичной эффективности",
  "omen-of-sinistral-necromancy": "Предзнаменование некромантии левши",
  "omen-of-the-blackblooded": "Предзнаменование чернокровных",
  "omen-of-putrefaction": "Предзнаменование разложения",
  "omen-of-bartering": "Предзнаменование бартера",
  "omen-of-corruption": "Предзнаменование осквернения",
  "omen-of-dextral-alchemy": "Предзнаменование алхимии правши",
  "omen-of-dextral-coronation": "Предзнаменование коронации правши",
  "omen-of-dextral-exaltation": "Предзнаменование возвышения правши",
  "omen-of-dextral-necromancy": "Предзнаменование некромантии правши",
  "omen-of-gambling": "Предзнаменование азарта",
  "omen-of-greater-annulment": "Предзнаменование великого очищения",
  "omen-of-homogenising-coronation": "Предзнаменование единой коронации",
  "omen-of-homogenising-exaltation": "Предзнаменование единого возвышения",
  "omen-of-recombination": "Предзнаменование рекомбинации",
  "omen-of-refreshment": "Предзнаменование восполнения",
  "omen-of-resurgence": "Предзнаменование возрождения",
  "omen-of-sinistral-alchemy": "Предзнаменование алхимии левши",
  "omen-of-sinistral-coronation": "Предзнаменование коронации левши",
  "omen-of-the-liege": "Предзнаменование властителя",
  "omen-of-the-sovereign": "Предзнаменование правителя",
  "twilight-reliquary-key": "Сумеречный ключ реликвария",
  "the-arbiters-reliquary-key": "Ключ реликвария Арбитра",
  "xeshts-reliquary-key": "Ключ реликвария Кшета",
  "ritualistic-reliquary-key": "Ритуалистический ключ реликвария",
  "olroths-reliquary-key": "Ключ реликвария Олрота",
  "the-trialmasters-reliquary-key": "Ключ реликвария Мастера испытаний",
  "against-the-darkness": "Ключ от Реликвария Зарока: Противление тьме",
  "tangmazus-reliquary-key": "Ключ реликвария Тангмазу",
  "temporalis": "Ключ от Реликвария Зарока: Темпоралис",
  "uul-netols-embrace": "Объятие Уул-Нетола",
  "xophs-blood": "Кровь Ксофа",
  "tul-fall": "Падение Тул",
  "eshs-breach": "Разлом Иш",
  "chayulas-breach": "Разлом Чаюлы",
  "splinter-of-uul-netol": "Осколок Уул-Нетола",
  "splinter-of-xoph": "Осколок Ксофа",
  "splinter-of-tul": "Осколок Тул",
  "splinter-of-esh": "Осколок Иш",
  "splinter-of-chayula": "Осколок Чаюлы",
  "breachstone-of-uul-netol": "Камень Разлома Уул-Нетола",
  "breachstone-of-xoph": "Камень Разлома Ксофа",
  "breachstone-of-tul": "Камень Разлома Тул",
  "breachstone-of-esh": "Камень Разлома Иш",
  "breachstone-of-chayula": "Камень Разлома Чаюлы",
  "rakiatas-flow": "Поток Ракиаты",
  "garukhans-resolve": "Решимость Гарухан",
  "gnawed-jawbone": "Обглоданная челюсть",
  "abyssal-wail": "Бездонный плач",
  "stibnite-doom": "Стибнитовая гибель",
  "profane-vigor": "Кощунственная сила",
  "uncut-skill-gem": "Неогранённый камень умения",
  "uncut-support-gem": "Неогранённый камень поддержки",
  "uncut-spirit-gem": "Неогранённый камень духа",
  "lineage-lifetap": "Кровопускание Аталуи",
  "lineage-omnicurse": "Пагуба Доэдре",
  "lineage-unbound-malice": "Мука Ишчейла",
  "diluted-liquid-ire": "Разбавленный жидкий гнев",
  "diluted-liquid-guilt": "Разбавленная жидкая вина",
  "diluted-liquid-greed": "Разбавленная жидкая жадность",
  "liquid-paranoia": "Жидкая паранойя",
  "liquid-envy": "Жидкая зависть",
  "liquid-disgust": "Жидкое отвращение",
  "liquid-despair": "Жидкое отчаяние",
  "concentrated-liquid-fear": "Концентрированный жидкий страх",
  "concentrated-liquid-suffering": "Концентрированное жидкое страдание",
  "concentrated-liquid-isolation": "Концентрированное жидкое отчуждение",
  "potent-liquid-contempt": "Густое жидкое презрение",
  "potent-liquid-ferocity": "Густая жидкая свирепость",
  "potent-liquid-melancholy": "Густая жидкая меланхолия",
  "ancient-potent-liquid-contempt": "Древнее густое жидкое презрение",
  "ancient-potent-liquid-ferocity": "Древняя густая жидкая свирепость",
  "ancient-potent-liquid-melancholy": "Древняя густая жидкая меланхолия",
  "ancient-concentrated-liquid-isolation": "Древнее концентрированное жидкое отчуждение",
  "ancient-concentrated-liquid-fear": "Древний концентрированный жидкий страх",
  "ancient-concentrated-liquid-suffering": "Древнее концентрированное жидкое страдание",
  "ancient-liquid-despair": "Древнее жидкое отчаяние",
  "ancient-liquid-disgust": "Древнее жидкое отвращение",
  "ancient-liquid-paranoia": "Древняя жидкая паранойя",
  "ancient-liquid-envy": "Древняя жидкая зависть",
  "ancient-diluted-liquid-greed": "Древняя разбавленная жидкая жадность",
  "ancient-diluted-liquid-guilt": "Древняя разбавленная жидкая вина",
  "ancient-diluted-liquid-ire": "Древний разбавленный жидкий гнев",
  "distilled-ire": "Дистиллированный гнев",
  "distilled-guilt": "Дистиллированная вина",
  "distilled-greed": "Дистиллированная жадность",
  "distilled-paranoia": "Дистиллированная паранойя",
  "distilled-envy": "Дистиллированная зависть",
  "distilled-disgust": "Дистиллированное отвращение",
  "distilled-despair": "Дистиллированное отчаяние",
  "distilled-fear": "Дистиллированный страх",
  "distilled-suffering": "Дистиллированное страдание",
  "distilled-isolation": "Дистиллированное отчуждение",
  "call-of-the-shadows": "Зов теней",
  "incursion-greater-vaal-orb": "Великая сфера Ваала вторжения",
  "incursion-vaal-orb": "Сфера Ваала вторжения",
  "fox-idol": "Идол лисы",
  "rabbit-idol": "Идол кролика",
  "wolf-idol": "Идол волка",
  "ox-idol": "Идол быка",
  "bear-idol": "Идол медведя",
  "boar-idol": "Идол кабана",
  "owl-idol": "Идол совы",
  "cat-idol": "Идол кошки",
  "stag-idol": "Идол оленя",
  "primate-idol": "Идол примата",
  "idol-of-ralakesh": "Идол Ралакеша",
  "idol-of-sirrius": "Идол Сирриуса",
  "idol-of-eramir": "Идол Эрамира",
  "idol-of-eeshta": "Идол Ишты",
  "idol-of-grold": "Идол Грольда",
  "idol-of-thruldana": "Идол Трулданы",
  "idol-of-egrin": "Идол Эгрина",
  "idol-of-maxarius": "Идол Макерия",
  "hawk-idol": "Идол ястреба",
  "panther-idol": "Идол пантеры",
  "snake-idol": "Идол змеи",
  "stoat-idol": "Идол горностая",
  "idol-of-alira": "Идол Алиры",
  "idol-of-greust": "Идол Груста",
  "idol-of-kraityn": "Идол Крайтина",
  "idol-of-oak": "Идол Дуба",
  "idol-of-silk": "Идол Шёлка",
  "idol-of-yeena": "Идол Йины",
  "idol-of-the-martyr": "Идол жертвы",
  "idol-of-the-pharisee": "Идол фарисея",
  "idol-of-the-sycophant": "Идол прислужника",
  "idolatry": "Идолопоклонство",
  "verisium-ore": "Веризиевая руда",
  "verisium-ingot": "Веризиевый слиток",
  "verisium-shard": "Веризиевый осколок",
  "vaal-orb-of-the-ancients": "Сфера Ваала древних",
  "corrupted-vaal-orb": "Осквернённая сфера Ваала",
  "xophs-catalyst": "Катализатор Ксофа",
  "eshs-catalyst": "Катализатор Иш",
  "tuls-catalyst": "Катализатор Тул",
  "chayulas-catalyst": "Катализатор Чаюлы",
  "adaptive-catalyst": "Адаптивный катализатор",
  "carapace-catalyst": "Панцирный катализатор",
  "flesh-catalyst": "Плотский катализатор",
  "neural-catalyst": "Невральный катализатор",
  "reaver-catalyst": "Разбойничий катализатор",
  "sibilant-catalyst": "Свистящий катализатор",
  "skittering-catalyst": "Шуршащий катализатор",
  "refined-adaptive-catalyst": "Очищенный адаптивный катализатор",
  "refined-carapace-catalyst": "Очищенный панцирный катализатор",
  "refined-chayulas-catalyst": "Очищенный катализатор Чаюлы",
  "refined-eshs-catalyst": "Очищенный катализатор Иш",
  "refined-flesh-catalyst": "Очищенный плотский катализатор",
  "refined-neural-catalyst": "Очищенный невральный катализатор",
  "refined-reaver-catalyst": "Очищенный разбойничий катализатор",
  "refined-sibilant-catalyst": "Очищенный свистящий катализатор",
  "refined-skittering-catalyst": "Очищенный шуршащий катализатор",
  "refined-tuls-catalyst": "Очищенный катализатор Тул",
  "refined-xophs-catalyst": "Очищенный катализатор Ксофа",
  "breach-catalyst-life": "Катализатор разлома: жизнь",
  "breach-catalyst-fire": "Катализатор разлома: огонь",
  "breach-catalyst-cold": "Катализатор разлома: холод",
  "breach-catalyst-lightning": "Катализатор разлома: молния",
};

// ---------------------------------------------------------------------------
// api_id → English name (offline fallback)
// ---------------------------------------------------------------------------

const CURRENCY_NAMES_EN: Record<string, string> = {
  "exalted": "Exalted Orb",
  "chaos": "Chaos Orb",
  "divine": "Divine Orb",
  "vaal": "Vaal Orb",
  "mirror": "Mirror of Kalandra",
  "alch": "Orb of Alchemy",
  "transmute": "Orb of Transmutation",
  "aug": "Orb of Augmentation",
  "chance": "Orb of Chance",
  "annul": "Orb of Annulment",
  "regal": "Regal Orb",
  "whetstone": "Blacksmith's Whetstone",
  "scrap": "Armourer's Scrap",
  "bauble": "Glassblower's Bauble",
  "gcp": "Gemcutter's Prism",
  "etcher": "Arcanist's Etcher",
  "artificers": "Artificer's Orb",
  "wisdom": "Scroll of Wisdom",
  "fracturing-orb": "Fracturing Orb",
  "chance-shard": "Chance Shard",
  "regal-shard": "Regal Shard",
  "artificers-shard": "Artificer's Shard",
  "transmutation-shard": "Transmutation Shard",
  "greater-chaos-orb": "Greater Chaos Orb",
  "greater-exalted-orb": "Greater Exalted Orb",
  "greater-orb-of-transmutation": "Greater Orb of Transmutation",
  "greater-orb-of-augmentation": "Greater Orb of Augmentation",
  "greater-regal-orb": "Greater Regal Orb",
  "greater-jewellers-orb": "Greater Jeweller's Orb",
  "lesser-jewellers-orb": "Lesser Jeweller's Orb",
  "perfect-chaos-orb": "Perfect Chaos Orb",
  "perfect-exalted-orb": "Perfect Exalted Orb",
  "perfect-jewellers-orb": "Perfect Jeweller's Orb",
  "perfect-orb-of-transmutation": "Perfect Orb of Transmutation",
  "perfect-orb-of-augmentation": "Perfect Orb of Augmentation",
  "perfect-regal-orb": "Perfect Regal Orb",
  "cryptic-key": "Cryptic Key",
  "hinekoras-lock": "Hinekora's Lock",
  "portal": "Portal Scroll",
  "identify": "Scroll of Identification",
  "scouring": "Orb of Scouring",
  "regret": "Orb of Regret",
  "fusings": "Orb of Fusing",
  "chromatic": "Chromatic Orb",
  "jeweller": "Jeweller's Orb",
  "blessed": "Blessed Orb",
  "eternal": "Eternal Orb",
  "silver": "Silver Coin",
  "gold": "Gold",
  "perandus": "Perandus Coin",
  "alteration": "Orb of Alteration",
  "raven-touched-shard": "Raven-Touched Shard",
  "head-of-the-king": "Head of the King",
  "astrids-creativity": "Astrid's Creativity",
  "fire-rune-tier-1": "Fire Rune Tier 1",
  "fire-rune-tier-2": "Fire Rune Tier 2",
  "fire-rune-tier-3": "Fire Rune Tier 3",
  "ice-rune-tier-1": "Ice Rune Tier 1",
  "ice-rune-tier-2": "Ice Rune Tier 2",
  "ice-rune-tier-3": "Ice Rune Tier 3",
  "lightning-rune-tier-1": "Lightning Rune Tier 1",
  "lightning-rune-tier-2": "Lightning Rune Tier 2",
  "lightning-rune-tier-3": "Lightning Rune Tier 3",
  "essence-of-enfeeblement": "Essence of Enfeeblement",
  "essence-of-sorrow": "Essence of Sorrow",
  "essence-of-rage": "Essence of Rage",
  "essence-of-suffering": "Essence of Suffering",
  "essence-of-wrath": "Essence of Wrath",
  "essence-of-doubt": "Essence of Doubt",
  "essence-of-anger": "Essence of Anger",
  "essence-of-torment": "Essence of Torment",
  "essence-of-fear": "Essence of Fear",
  "essence-of-horror": "Essence of Horror",
  "essence-of-delirium": "Essence of Delirium",
  "essence-of-hysteria": "Essence of Hysteria",
  "essence-of-insanity": "Essence of Insanity",
  "deafening-essence-of-enfeeblement": "Deafening Essence of Enfeeblement",
  "deafening-essence-of-sorrow": "Deafening Essence of Sorrow",
  "deafening-essence-of-rage": "Deafening Essence of Rage",
  "deafening-essence-of-suffering": "Deafening Essence of Suffering",
  "deafening-essence-of-wrath": "Deafening Essence of Wrath",
  "deafening-essence-of-doubt": "Deafening Essence of Doubt",
  "deafening-essence-of-anger": "Deafening Essence of Anger",
  "deafening-essence-of-torment": "Deafening Essence of Torment",
  "deafening-essence-of-fear": "Deafening Essence of Fear",
  "deafening-essence-of-horror": "Deafening Essence of Horror",
  "deafening-essence-of-delirium": "Deafening Essence of Delirium",
  "deafening-essence-of-hysteria": "Deafening Essence of Hysteria",
  "deafening-essence-of-insanity": "Deafening Essence of Insanity",
  "life-essence": "Life Essence",
  "mana-essence": "Mana Essence",
  "soul-core-of-quipolatl": "Soul Core of Quipolatl",
  "soul-core-of-azcapa": "Soul Core of Azcapa",
  "soul-core-of-opiloti": "Soul Core of Opiloti",
  "soul-core-of-zalatl": "Soul Core of Zalatl",
  "soul-core-of-cholotl": "Soul Core of Cholotl",
  "soul-core-of-tacati": "Soul Core of Tacati",
  "soul-core-of-citaqualotl": "Soul Core of Citaqualotl",
  "soul-core-of-jiquani": "Soul Core of Jiquani",
  "soul-core-of-zantipi": "Soul Core of Zantipi",
  "soul-core-of-ticaba": "Soul Core of Ticaba",
  "soul-core-of-topotante": "Soul Core of Topotante",
  "soul-core-of-xopec": "Soul Core of Xopec",
  "soul-core-of-atmohua": "Soul Core of Atmohua",
  "soul-core-of-tzamoto": "Soul Core of Tzamoto",
  "soul-core-of-puhuarte": "Soul Core of Puhuarte",
  "opilotis-soul-core-of-assault": "Opiloti's Soul Core of Assault",
  "xopecs-soul-core-of-power": "Xopec's Soul Core of Power",
  "quipolatls-soul-core-of-flow": "Quipolatl's Soul Core of Flow",
  "tzamotos-soul-core-of-ferocity": "Tzamoto's Soul Core of Ferocity",
  "guatelitzis-soul-core-of-endurance": "Guatelitzi's Soul Core of Endurance",
  "estazuntis-soul-core-of-convalescence": "Estazunti's Soul Core of Convalescence",
  "xipocados-soul-core-of-dominion": "Xipocado's Soul Core of Dominion",
  "tacatis-soul-core-of-affliction": "Tacati's Soul Core of Affliction",
  "hayoxis-soul-core-of-heatproofing": "Hayoxi's Soul Core of Heatproofing",
  "atmohuas-soul-core-of-retreat": "Atmohua's Soul Core of Retreat",
  "aldurs-saga": "Aldur's Saga",
  "olroths-conviction": "Olroth's Conviction",
  "rigwalds-ferocity": "Rigwald's Ferocity",
  "voranas-siege": "Vorana's Siege",
  "gwenithas-gamble": "Gwenitha's Gamble",
  "medveds-might": "Medved's Might",
  "tujen-penny": "Tujen's Penny",
  "rostas-faith": "Rosta's Faith",
  "ursas-resolution": "Ursa's Resolution",
  "sukaas-dash": "Sukaa's Dash",
  "dannigs-honour": "Dannig's Honour",
  "kalguur-rune": "Kalguur Rune",
  "expedition-logbook": "Expedition Logbook",
  "artifact-of-the-chayula": "Artifact of the Chayula",
  "artifact-of-the-vaal": "Artifact of the Vaal",
  "artifact-of-the-abyss": "Artifact of the Abyss",
  "artifact-of-the-breach": "Artifact of the Breach",
  "sun-touched-helmet": "Sun-Touched Helmet",
  "sun-touched-armour": "Sun-Touched Armour",
  "sun-touched-gloves": "Sun-Touched Gloves",
  "sun-touched-boots": "Sun-Touched Boots",
  "sun-touched-weapon": "Sun-Touched Weapon",
  "omen-of-whittling": "Omen of Whittling",
  "omen-of-chance": "Omen of Chance",
  "omen-of-light": "Omen of Light",
  "omen-of-abyssal-echoes": "Omen of Abyssal Echoes",
  "omen-of-amelioration": "Omen of Amelioration",
  "omen-of-sinistral-erasure": "Omen of Sinistral Erasure",
  "omen-of-sinistral-annulment": "Omen of Sinistral Annulment",
  "omen-of-dextral-annulment": "Omen of Dextral Annulment",
  "omen-of-dextral-erasure": "Omen of Dextral Erasure",
  "omen-of-sinistral-crystallisation": "Omen of Sinistral Crystallisation",
  "omen-of-dextral-crystallisation": "Omen of Dextral Crystallisation",
  "omen-of-sinistral-exaltation": "Omen of Sinistral Exaltation",
  "omen-of-greater-exaltation": "Omen of Greater Exaltation",
  "omen-of-sanctification": "Omen of Sanctification",
  "omen-of-the-blessed": "Omen of the Blessed",
  "omen-of-catalysing-exaltation": "Omen of Catalysing Exaltation",
  "omen-of-the-hunt": "Omen of the Hunt",
  "omen-of-secret-compartments": "Omen of Secret Compartments",
  "omen-of-reinforcements": "Omen of Reinforcements",
  "omen-of-answered-prayers": "Omen of Answered Prayers",
  "omen-of-the-ancients": "Omen of the Ancients",
  "omen-of-chaotic-quantity": "Omen of Chaotic Quantity",
  "omen-of-chaotic-monsters": "Omen of Chaotic Monsters",
  "omen-of-chaotic-rarity": "Omen of Chaotic Rarity",
  "omen-of-chaotic-effectiveness": "Omen of Chaotic Effectiveness",
  "omen-of-sinistral-necromancy": "Omen of Sinistral Necromancy",
  "omen-of-the-blackblooded": "Omen of the Blackblooded",
  "omen-of-putrefaction": "Omen of Putrefaction",
  "omen-of-bartering": "Omen of Bartering",
  "twilight-reliquary-key": "Twilight Reliquary Key",
  "the-arbiters-reliquary-key": "The Arbiter's Reliquary Key",
  "xeshts-reliquary-key": "Xesht's Reliquary Key",
  "ritualistic-reliquary-key": "Ritualistic Reliquary Key",
  "olroths-reliquary-key": "Olroth's Reliquary Key",
  "the-trialmasters-reliquary-key": "The Trialmaster's Reliquary Key",
  "against-the-darkness": "Against the Darkness",
  "tangmazus-reliquary-key": "Tangmazu's Reliquary Key",
  "temporalis": "Zarokh's Reliquary Key: Temporalis",
  "uul-netols-embrace": "Uul-Netol's Embrace",
  "xophs-blood": "Xoph's Blood",
  "tul-fall": "Tul's Fall",
  "eshs-breach": "Esh's Breach",
  "chayulas-breach": "Chayula's Breach",
  "splinter-of-uul-netol": "Splinter of Uul-Netol",
  "splinter-of-xoph": "Splinter of Xoph",
  "splinter-of-tul": "Splinter of Tul",
  "splinter-of-esh": "Splinter of Esh",
  "splinter-of-chayula": "Splinter of Chayula",
  "breachstone-of-uul-netol": "Breachstone of Uul-Netol",
  "breachstone-of-xoph": "Breachstone of Xoph",
  "breachstone-of-tul": "Breachstone of Tul",
  "breachstone-of-esh": "Breachstone of Esh",
  "breachstone-of-chayula": "Breachstone of Chayula",
  "breach-catalyst-life": "Breach Catalyst: Life",
  "breach-catalyst-fire": "Breach Catalyst: Fire",
  "breach-catalyst-cold": "Breach Catalyst: Cold",
  "breach-catalyst-lightning": "Breach Catalyst: Lightning",
  "rakiatas-flow": "Rakiata's Flow",
  "garukhans-resolve": "Garukhan's Resolve",
  "gnawed-jawbone": "Gnawed Jawbone",
  "abyssal-wail": "Abyssal Wail",
  "stibnite-doom": "Stibnite Doom",
  "profane-vigor": "Profane Vigor",
  "uncut-skill-gem": "Uncut Skill Gem",
  "uncut-support-gem": "Uncut Support Gem",
  "uncut-spirit-gem": "Uncut Spirit Gem",
  "lineage-lifetap": "Lineage: Lifetap",
  "lineage-omnicurse": "Lineage: Omnicurse",
  "lineage-unbound-malice": "Lineage: Unbound Malice",
  "diluted-liquid-ire": "Diluted Liquid Ire",
  "diluted-liquid-guilt": "Diluted Liquid Guilt",
  "diluted-liquid-greed": "Diluted Liquid Greed",
  "liquid-paranoia": "Liquid Paranoia",
  "liquid-envy": "Liquid Envy",
  "liquid-disgust": "Liquid Disgust",
  "liquid-despair": "Liquid Despair",
  "concentrated-liquid-fear": "Concentrated Liquid Fear",
  "concentrated-liquid-suffering": "Concentrated Liquid Suffering",
  "concentrated-liquid-isolation": "Concentrated Liquid Isolation",
  "potent-liquid-contempt": "Potent Liquid Contempt",
  "potent-liquid-ferocity": "Potent Liquid Ferocity",
  "potent-liquid-melancholy": "Potent Liquid Melancholy",
  "ancient-potent-liquid-contempt": "Ancient Potent Liquid Contempt",
  "ancient-potent-liquid-ferocity": "Ancient Potent Liquid Ferocity",
  "ancient-potent-liquid-melancholy": "Ancient Potent Liquid Melancholy",
  "ancient-concentrated-liquid-isolation": "Ancient Concentrated Liquid Isolation",
  "ancient-concentrated-liquid-fear": "Ancient Concentrated Liquid Fear",
  "ancient-concentrated-liquid-suffering": "Ancient Concentrated Liquid Suffering",
  "ancient-liquid-despair": "Ancient Liquid Despair",
  "ancient-liquid-disgust": "Ancient Liquid Disgust",
  "ancient-liquid-paranoia": "Ancient Liquid Paranoia",
  "ancient-liquid-envy": "Ancient Liquid Envy",
  "ancient-diluted-liquid-greed": "Ancient Diluted Liquid Greed",
  "ancient-diluted-liquid-guilt": "Ancient Diluted Liquid Guilt",
  "distilled-ire": "Distilled Ire",
  "distilled-guilt": "Distilled Guilt",
  "distilled-greed": "Distilled Greed",
  "distilled-paranoia": "Distilled Paranoia",
  "distilled-envy": "Distilled Envy",
  "distilled-disgust": "Distilled Disgust",
  "distilled-despair": "Distilled Despair",
  "distilled-fear": "Distilled Fear",
  "distilled-suffering": "Distilled Suffering",
  "distilled-isolation": "Distilled Isolation",
  "call-of-the-shadows": "Call of the Shadows",
  "incursion-greater-vaal-orb": "Incursion Greater Vaal Orb",
  "incursion-vaal-orb": "Incursion Vaal Orb",
  "fox-idol": "Fox Idol",
  "rabbit-idol": "Rabbit Idol",
  "wolf-idol": "Wolf Idol",
  "ox-idol": "Ox Idol",
  "bear-idol": "Bear Idol",
  "boar-idol": "Boar Idol",
  "owl-idol": "Owl Idol",
  "cat-idol": "Cat Idol",
  "stag-idol": "Stag Idol",
  "primate-idol": "Primate Idol",
  "idol-of-ralakesh": "Idol of Ralakesh",
  "idol-of-sirrius": "Idol of Sirrius",
  "idol-of-eramir": "Idol of Eramir",
  "idol-of-eeshta": "Idol of Eeshta",
  "idol-of-grold": "Idol of Grold",
  "idol-of-thruldana": "Idol of Thruldana",
  "idol-of-egrin": "Idol of Egrin",
  "idol-of-maxarius": "Idol of Maxarius",
  "verisium-ore": "Verisium Ore",
  "verisium-ingot": "Verisium Ingot",
  "verisium-shard": "Verisium Shard",
  "vaal-orb-of-the-ancients": "Vaal Orb of the Ancients",
  "corrupted-vaal-orb": "Corrupted Vaal Orb",
};

// ---------------------------------------------------------------------------
// Lookup functions
// ---------------------------------------------------------------------------

/**
 * Get the Russian display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyRuName(apiId: string): string | null {
  return CURRENCY_NAMES_RU[apiId] ?? CURRENCY_NAMES_RU[apiId.toLowerCase()] ?? null;
}

/**
 * Get the English display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyEnName(apiId: string): string | null {
  return CURRENCY_NAMES_EN[apiId] ?? CURRENCY_NAMES_EN[apiId.toLowerCase()] ?? null;
}

/**
 * Get a display name for a currency pair like "exalted/chaos".
 * Uses Russian names if available, falls back to api_ids.
 */
export function getCurrencyPairDisplayName(
  pairStr: string,
  locale: "ru" | "en" = "ru",
): string {
  const parts = pairStr.split("/");
  if (parts.length !== 2) return pairStr;

  const lookup = locale === "ru" ? getCurrencyRuName : getCurrencyEnName;
  const from = lookup(parts[0]) ?? parts[0];
  const to = lookup(parts[1]) ?? parts[1];
  return `${from}/${to}`;
}
