#!/usr/bin/env python3
"""
sync_currency_names_ts.py — Regenerate src/lib/currency-names.ts from
backend/data/currency_names.json.

The TS file is a hand-mirrored copy of the JSON data so the client-side code
has an offline fallback. This script regenerates it from the canonical JSON
source, ensuring the two stay in sync.

Run after every currency_names.json update (e.g. after running the
sync_currency_names_from_poe2db.py pipeline).

Usage:
    python scripts/sync_currency_names_ts.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = REPO_ROOT / "backend" / "data" / "currency_names.json"
TS_PATH = REPO_ROOT / "src" / "lib" / "currency-names.ts"


def ts_escape(s: str) -> str:
    """Escape a string for use as a TypeScript double-quoted string literal."""
    # Escape backslash, double-quote, newline, tab, CR
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{s}"'


def main() -> int:
    if not JSON_PATH.exists():
        print(f"ERROR: missing {JSON_PATH}", file=sys.stderr)
        return 1
    with JSON_PATH.open(encoding="utf-8") as f:
        data = json.load(f)

    cat_ru = data["category_names_ru"]
    cat_en = data["category_names_en"]
    cur_ru = data["currency_names_ru"]
    cur_en = data["currency_names_en"]

    if set(cat_ru.keys()) != set(cat_en.keys()):
        print("ERROR: category_names_ru/en key drift in JSON", file=sys.stderr)
        return 1
    if set(cur_ru.keys()) != set(cur_en.keys()):
        print("ERROR: currency_names_ru/en key drift in JSON", file=sys.stderr)
        return 1

    lines: list[str] = []
    lines.append("/**")
    lines.append(" * Client-side api_id → display name mapping for PoE2 currencies and items.")
    lines.append(" *")
    lines.append(" * PURPOSE:")
    lines.append(" *   When the backend is online, flip responses include `currencyFromRu` /")
    lines.append(" *   `currencyToRu` fields from `backend/data/currency_names_ru.py`.")
    lines.append(" *   This file provides a FALLBACK for:")
    lines.append(" *     1. Offline mode (backend down, only cache/prepopulated data available)")
    lines.append(" *     2. Items not yet in the backend mapping")
    lines.append(" *     3. Currencies table, exchange table, and other non-flip views")
    lines.append(" *")
    lines.append(" * USAGE:")
    lines.append(" *   import { getCurrencyRuName, getCurrencyEnName } from \"@/lib/currency-names\";")
    lines.append(" *   const ruName = getCurrencyRuName(\"exalted\"); // \"Благородная сфера\"")
    lines.append(" *")
    lines.append(" * MAINTAINER NOTES:")
    lines.append(" *   - AUTO-GENERATED by scripts/sync_currency_names_ts.py from")
    lines.append(" *     backend/data/currency_names.json. Do NOT edit by hand.")
    lines.append(" *   - Run `python scripts/sync_currency_names_ts.py` after every JSON update.")
    lines.append(" *   - The full backend mirror is the source of truth — this file is a 1:1 copy.")
    lines.append(" *   - PoE1-only items have been removed — this is a PoE2-only dashboard.")
    lines.append(" */")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// api_id → Russian name (offline fallback)")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("const CURRENCY_NAMES_RU: Record<string, string> = {")
    for key in cur_ru:
        lines.append(f"  {ts_escape(key)}: {ts_escape(cur_ru[key])},")
    lines.append("};")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// api_id → English name (offline fallback)")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("const CURRENCY_NAMES_EN: Record<string, string> = {")
    for key in cur_en:
        lines.append(f"  {ts_escape(key)}: {ts_escape(cur_en[key])},")
    lines.append("};")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// category slug → Russian label")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("const CATEGORY_NAMES_RU: Record<string, string> = {")
    for key in cat_ru:
        lines.append(f"  {ts_escape(key)}: {ts_escape(cat_ru[key])},")
    lines.append("};")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// category slug → English label")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("const CATEGORY_NAMES_EN: Record<string, string> = {")
    for key in cat_en:
        lines.append(f"  {ts_escape(key)}: {ts_escape(cat_en[key])},")
    lines.append("};")
    lines.append("")
    # Append the helper functions from the existing file
    lines.append("""/**
 * Get the Russian display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyRuName(apiId: string): string | null {
  if (!apiId) return null;
  return CURRENCY_NAMES_RU[apiId] ?? CURRENCY_NAMES_RU[apiId.toLowerCase()] ?? null;
}

/**
 * Get the English display name for a currency by api_id.
 * Falls back to the api_id itself if no mapping exists.
 */
export function getCurrencyEnName(apiId: string): string | null {
  return CURRENCY_NAMES_EN[apiId] ?? CURRENCY_NAMES_EN[apiId.toLowerCase()] ?? null;
}

/**
 * Get the Russian display name for a POE2Scout category slug.
 * Falls back to the slug itself (title-cased) if no mapping exists.
 *
 * Example: "ritual" → "Омены ритуала"
 */
export function getCategoryRuName(slug: string): string | null {
  if (!slug) return null;
  return CATEGORY_NAMES_RU[slug] ?? CATEGORY_NAMES_RU[slug.toLowerCase()] ?? null;
}

/**
 * Get the English display name for a POE2Scout category slug.
 * Falls back to the slug itself (title-cased) if no mapping exists.
 */
export function getCategoryEnName(slug: string): string | null {
  if (!slug) return null;
  return CATEGORY_NAMES_EN[slug] ?? CATEGORY_NAMES_EN[slug.toLowerCase()] ?? null;
}

/**
 * Localize a currency name based on the active locale.
 * Returns `null` when no mapping exists — callers should provide their own
 * fallback (typically the upstream `text` field from POE2Scout or the raw
 * api_id). This keeps the helper composable with `||` fallbacks.
 *
 * Accepts any locale string but only RU has a full translation map;
 * other locales fall back to English names.
 */
export function getCurrencyDisplayName(
  apiId: string,
  locale: string = "ru",
): string | null {
  const lookup = locale === "ru" ? getCurrencyRuName : getCurrencyEnName;
  return lookup(apiId);
}

/**
 * Localize a category slug based on the active locale.
 * Returns the slug as-is when no mapping exists (categories are a small
 * fixed set, so fallback is safe).
 */
export function getCategoryDisplayName(
  slug: string,
  locale: string = "ru",
): string {
  const lookup = locale === "ru" ? getCategoryRuName : getCategoryEnName;
  return lookup(slug) ?? slug;
}

/**
 * Get a display name for a currency pair like "exalted/chaos".
 * Uses Russian names if available, falls back to api_ids.
 */
export function getCurrencyPairDisplayName(
  pairStr: string,
  locale: "ru" | "en" = "ru",
): string {
  const parts = pairStr.split("/");
  if (parts.length !== 2) return pairStr;

  const lookup = locale === "ru" ? getCurrencyRuName : getCurrencyEnName;
  const from = lookup(parts[0]) ?? parts[0];
  const to = lookup(parts[1]) ?? parts[1];
  return `${from}/${to}`;
}
""")

    content = "\n".join(lines)
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with TS_PATH.open("w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {TS_PATH.relative_to(REPO_ROOT)} — {len(cur_ru)} RU + {len(cur_en)} EN + {len(cat_ru)} categories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
